[build]
  command = "./build.sh"
  functions = "functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8889

[build.environment]
  GO_IMPORT_PATH = "github.com/nickgraffis/netlify-go-function-demo"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
